package Jeux

import "fmt"

func Error() {
	if LosePoint == 1 {
		fmt.Println("")
		fmt.Println("    ")
		fmt.Println("    ")
		fmt.Println("    ")
		fmt.Println("    ")
		fmt.Println("    ")
		fmt.Println("     ")
		fmt.Println("     ")
		fmt.Println("    ")
		fmt.Println("     ")
		fmt.Println(LightGreen, " ___________", Reset)
	} else if LosePoint == 2 {
		fmt.Println(LightGreen, "      []", Reset)
		fmt.Println(LightGreen, "      []    ", Reset)
		fmt.Println(LightGreen, "      []        ", Reset)
		fmt.Println(LightGreen, "      []         ", Reset)
		fmt.Println(LightGreen, "      []              ", Reset)
		fmt.Println(LightGreen, "      []   ", Reset)
		fmt.Println(LightGreen, "      []      ", Reset)
		fmt.Println(LightGreen, "      []        ", Reset)
		fmt.Println(LightGreen, "      []         ", Reset)
		fmt.Println(LightGreen, "      []")
		fmt.Println(LightGreen, " _____[]______", Reset)
	} else if LosePoint == 3 {
		fmt.Println(DarkGreen, "      []", Reset)
		fmt.Println(DarkGreen, "      []            ", Reset)
		fmt.Println(DarkGreen, "      []         ", Reset)
		fmt.Println(DarkGreen, "      []          ", Reset)
		fmt.Println(DarkGreen, "      []              ", Reset)
		fmt.Println(DarkGreen, "      []          ", Reset)
		fmt.Println(DarkGreen, "      []       ", Reset)
		fmt.Println(DarkGreen, "      []         ", Reset)
		fmt.Println(DarkGreen, "      []            ", Reset)
		fmt.Println(DarkGreen, "      []\\")
		fmt.Println(DarkGreen, " _____[]_\\____", Reset)
	} else if LosePoint == 4 {
		fmt.Println(LightYellow, "======[]==============|========", Reset)
		fmt.Println(LightYellow, "      []           ", Reset)
		fmt.Println(LightYellow, "      []         ", Reset)
		fmt.Println(LightYellow, "      []           ", Reset)
		fmt.Println(LightYellow, "      []           ", Reset)
		fmt.Println(LightYellow, "      []          ", Reset)
		fmt.Println(LightYellow, "      []           ", Reset)
		fmt.Println(LightYellow, "      []           ", Reset)
		fmt.Println(LightYellow, "      []           ", Reset)
		fmt.Println(LightYellow, "      []\\", Reset)
		fmt.Println(LightYellow, " _____[]_\\____", Reset)
	} else if LosePoint == 5 {
		fmt.Println(OrangeYellow, "======[]==============|========", Reset)
		fmt.Println(OrangeYellow, "      []              |", Reset)
		fmt.Println(OrangeYellow, "      []            ", Reset)
		fmt.Println(OrangeYellow, "      []          ", Reset)
		fmt.Println(OrangeYellow, "      []              ", Reset)
		fmt.Println(OrangeYellow, "      []         ", Reset)
		fmt.Println(OrangeYellow, "      []          ", Reset)
		fmt.Println(OrangeYellow, "      []           ", Reset)
		fmt.Println(OrangeYellow, "      []        ", Reset)
		fmt.Println(OrangeYellow, "      []\\", Reset)
		fmt.Println(OrangeYellow, " _____[]_\\____", Reset)
	} else if LosePoint == 6 {
		fmt.Println(LightOrange, "======[]==============|========", Reset)
		fmt.Println(LightOrange, "      []            __|__", Reset)
		fmt.Println(LightOrange, "      []            |   |", Reset)
		fmt.Println(LightOrange, "      []            |___|", Reset)
		fmt.Println(LightOrange, "      []              ", Reset)
		fmt.Println(LightOrange, "      []          ", Reset)
		fmt.Println(LightOrange, "      []            ", Reset)
		fmt.Println(LightOrange, "      []             ", Reset)
		fmt.Println(LightOrange, "      []            ", Reset)
		fmt.Println(LightOrange, "      []\\", Reset)
		fmt.Println(LightOrange, " _____[]_\\____", Reset)
	} else if LosePoint == 7 {
		fmt.Println(LightOrange, "======[]==============|========")
		fmt.Println(LightOrange, "      []            __|__", Reset)
		fmt.Println(LightOrange, "      []            |   |", Reset)
		fmt.Println(LightOrange, "      []            |___|", Reset)
		fmt.Println(LightOrange, "      []              |", Reset)
		fmt.Println(LightOrange, "      []              |", Reset)
		fmt.Println(LightOrange, "      []              |", Reset)
		fmt.Println(LightOrange, "      []               ", Reset)
		fmt.Println(LightOrange, "      []           ", Reset)
		fmt.Println(LightOrange, "      []\\", Reset)
		fmt.Println(LightOrange, " _____[]_\\____", Reset)
	} else if LosePoint == 8 {
		fmt.Println(PinkRed, "======[]==============|========", Reset)
		fmt.Println(PinkRed, "      []            __|__", Reset)
		fmt.Println(PinkRed, "      []            |   |", Reset)
		fmt.Println(PinkRed, "      []            |___|", Reset)
		fmt.Println(PinkRed, "      []              |", Reset)
		fmt.Println(PinkRed, "      []              |\\", Reset)
		fmt.Println(PinkRed, "      []              | \\", Reset)
		fmt.Println(PinkRed, "      []              ", Reset)
		fmt.Println(PinkRed, "      []            ", Reset)
		fmt.Println(PinkRed, "      []\\", Reset)
		fmt.Println(PinkRed, " _____[]_\\____", Reset)
	} else if LosePoint == 9 {
		fmt.Println(PinkRed, "======[]==============|========", Reset)
		fmt.Println(PinkRed, "      []            __|__", Reset)
		fmt.Println(PinkRed, "      []            |   |", Reset)
		fmt.Println(PinkRed, "      []            |___|", Reset)
		fmt.Println(PinkRed, "      []              |", Reset)
		fmt.Println(PinkRed, "      []             /|\\", Reset)
		fmt.Println(PinkRed, "      []            / | \\", Reset)
		fmt.Println(PinkRed, "      []             ", Reset)
		fmt.Println(PinkRed, "      []            ", Reset)
		fmt.Println(PinkRed, "      []\\", Reset)
		fmt.Println(PinkRed, " _____[]_\\____", Reset)
	} else if LosePoint == 10 {
		fmt.Println(LightRed, "======[]==============|========", Reset)
		fmt.Println(LightRed, "      []            __|__", Reset)
		fmt.Println(LightRed, "      []            |   |", Reset)
		fmt.Println(LightRed, "      []            |___|", Reset)
		fmt.Println(LightRed, "      []              |", Reset)
		fmt.Println(LightRed, "      []             /|\\", Reset)
		fmt.Println(LightRed, "      []            / | \\", Reset)
		fmt.Println(LightRed, "      []               \\", Reset)
		fmt.Println(LightRed, "      []                \\", Reset)
		fmt.Println(LightRed, "      []\\", Reset)
		fmt.Println(LightRed, " _____[]_\\____", Reset)
	} else if LosePoint >= 11 {
		fmt.Println(LightRed, "======[]==============|========", Reset)
		fmt.Println(LightRed, "      []            __|__", Reset)
		fmt.Println(LightRed, "      []            |   |", Reset)
		fmt.Println(LightRed, "      []            |___|", Reset)
		fmt.Println(LightRed, "      []              |", Reset)
		fmt.Println(LightRed, "      []             /|\\", Reset)
		fmt.Println(LightRed, "      []            / | \\", Reset)
		fmt.Println(LightRed, "      []             / \\", Reset)
		fmt.Println(LightRed, "      []            /   \\", Reset)
		fmt.Println(LightRed, "      []\\", Reset)
		fmt.Println(LightRed, " _____[]_\\____", Reset)
	} else if LosePoint == 0 {
		fmt.Println("")
	}
}
